FROM node:22.2.0

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of the application files
COPY . .

# Expose any required ports
EXPOSE 4001

# Define the start command
CMD ["npm", "start"]